CREATE DATABASE BanHangNGK;

USE BanHangNGK;

CREATE TABLE NhaCungCap
(
	MaNCC NVARCHAR(25) PRIMARY KEY NOT NULL,
	TenNCC NVARCHAR(40),
	DiaChi NVARCHAR(50),
	SDT VARCHAR(20)
);

CREATE TABLE LoaiNuocGiaiKhat
(
	MaLoai NVARCHAR(25) PRIMARY KEY NOT NULL,
	TenLoai NVARCHAR(40),
	MaNCC NVARCHAR(25),
	FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC) ON DELETE CASCADE
);

CREATE TABLE DonDatHang
(
	MaDDH NVARCHAR(25) PRIMARY KEY NOT NULL,
	NgayDH DATE,
	MaNCC NVARCHAR(25),
	FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC) ON DELETE CASCADE
);

CREATE TABLE NuocGiaiKhat
(
	MaNGK NVARCHAR(25) PRIMARY KEY NOT NULL,
	TenNGK NVARCHAR(40),
	MaLoai NVARCHAR(25),
	FOREIGN KEY (MaLoai) REFERENCES LoaiNuocGiaiKhat(MaLoai) ON DELETE CASCADE
);

CREATE TABLE ChiTietDonDatHang
(
    MaDDH NVARCHAR(25),
    MaNGK NVARCHAR(25) NULL, 
    SoLuongDat INT,
    PRIMARY KEY (MaDDH),
    FOREIGN KEY (MaDDH) REFERENCES DonDatHang(MaDDH) ON DELETE CASCADE, -- Giữ cascade cho MaDDH
    FOREIGN KEY (MaNGK) REFERENCES NuocGiaiKhat(MaNGK) ON DELETE NO ACTION -- Thay đổi thành NO ACTION để tránh cascade
);



CREATE TABLE PhieuGiaoHang
(
	MaPhieuGH NVARCHAR(25) PRIMARY KEY NOT NULL,
	MaDDH NVARCHAR(25),
	FOREIGN KEY (MaDDH) REFERENCES DonDatHang(MaDDH) ON DELETE CASCADE
);

CREATE TABLE ChiTietPhieuGiaoHang
(
    MaPhieuGH NVARCHAR(25),
    MaNGK NVARCHAR(25),
    SoLuongGiao INT,
    DonGiaGiao FLOAT,
    PRIMARY KEY (MaPhieuGH, MaNGK),
    FOREIGN KEY (MaPhieuGH) REFERENCES PhieuGiaoHang(MaPhieuGH) ON DELETE CASCADE, -- Giữ cascade cho MaPhieuGH
    FOREIGN KEY (MaNGK) REFERENCES NuocGiaiKhat(MaNGK) ON DELETE NO ACTION -- Thay đổi thành NO ACTION cho MaNGK
);

CREATE TABLE KhachHang
(
	MaKH NVARCHAR(25) PRIMARY KEY NOT NULL,
	TenKH NVARCHAR(40),
	DiaChi NVARCHAR(50),
	SDT VARCHAR(15)
);

CREATE TABLE PhieuHen
(
	MaPhieuHen NVARCHAR(25) PRIMARY KEY NOT NULL,
	MaKH NVARCHAR(25),
	NgayLap DATE,
	NgayHen DATE,
	FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE
);

CREATE TABLE ChiTietPhieuHen
(
	MaPhieuHen NVARCHAR(25),
	MaNGK NVARCHAR(25),
	SoLuongHen INT,
	PRIMARY KEY (MaPhieuHen, MaNGK),
	FOREIGN KEY (MaPhieuHen) REFERENCES PhieuHen(MaPhieuHen) ON DELETE CASCADE,
	FOREIGN KEY (MaNGK) REFERENCES NuocGiaiKhat(MaNGK) ON DELETE CASCADE
);

CREATE TABLE HoaDon
(
	MaHD NVARCHAR(25) PRIMARY KEY NOT NULL,
	NgayLapHD DATE,
	MaKH NVARCHAR(25),
	FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE
);

CREATE TABLE ChiTietHoaDon
(
	MaHD NVARCHAR(25),
	MaNGK NVARCHAR(25),
	SoLuongMua INT,
	DonGiaBan FLOAT,
	PRIMARY KEY (MaHD, MaNGK),
	FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD) ON DELETE CASCADE,
	FOREIGN KEY (MaNGK) REFERENCES NuocGiaiKhat(MaNGK) ON DELETE CASCADE
);

CREATE TABLE PhieuTraNo
(
	MaPhieuTraNo NVARCHAR(25) PRIMARY KEY NOT NULL,
	NgayTra DATE,
	SoTienTra FLOAT,
	MaHD NVARCHAR(25),
	FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD) ON DELETE CASCADE
);

CREATE TABLE USERS
(
	TenDN VARCHAR(30) PRIMARY KEY NOT NULL,
	MatKhau VARCHAR(30)
);

INSERT INTO USERS VALUES
('Khoa','1'),
('Hiep','1'),
('Phuong','1'),
('An','1'),
('Dat','1');
